### ISSUE TITLE
Out of GPU memory though multi GPUs are there

### ISSUE THREAD

**Issue by guodong1988** [SantiagoMille/germinal#34]
Actually there are multi-GPUs in the computer, and the error shows only one GPU is used. How to solve the error? Thank you.

RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB. GPU 0 has a total capacity of 31.36 GiB of which 462.06 MiB is free. Including non-PyTorch memory, this process has 30.88 GiB memory in use. Of the allocated memory 5.94 GiB is allocated by PyTorch, and 673.03 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by guodong1988** [comment]
It works for me now, prepend the PYTORCH_CUDA_ALLOC_CONF environment variable to my command: PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True python run_germinal.py run=....

**Comment by guodong1988** [comment]
Same errors occurs again, when I set CDR3 = 12, but CDR3 = 8 to 25 except 12 works normally. There are multi-GPUs in the computer, but only GPU 0 are using for germinal. How to solve this problem. plz, plz, plz

**Comment by SantiagoMille** [comment]
hey @guodong1988, sorry to hear you’re hitting this error again.

Right now Germinal only uses one GPU per process. There’s no built-in multi-GPU / data-parallel support yet. So it’s expected that only a single GPU is busy, and adding more GPUs unfortunately doesn’t increase the available memory for a single run.

I saw a similar error when debugging Germinal. Sometimes after killing a run, a process can stay resident in VRAM and cause the next run to OOM immediately. If you’re using tmux, you can flip between terminals and watch GPU usage with `nvidia-smi` throughout the pipeline to make sure no “zombie” processes are hanging around. You can also try: `export XLA_CLIENT_MEM_FRACTION=0.5` but this will most likely only help if the issues is thrown during AbMPNN, AF3/Chai, etc. 

Could you share a few more details so we can narrow it down?

- At what stage of the run do you see the OOM?
- What GPU are you using and how much memory does it have?
- What target (or approximate target size)?
- scFv or nb?
- The full config you’re running Germinal with.

That info will make it much easier to reproduce and suggest a concrete fix.

**Comment by guodong1988** [comment]
> hey [@guodong1988](https://github.com/guodong1988), sorry to hear you’re hitting this error again.
> 
> Right now Germinal only uses one GPU per process. There’s no built-in multi-GPU / data-parallel support yet. So it’s expected that only a single GPU is busy, and adding more GPUs unfortunately doesn’t increase the available memory for a single run.
> 
> I saw a similar error when debugging Germinal. Sometimes after killing a run, a process can stay resident in VRAM and cause the next run to OOM immediately. If you’re using tmux, you can flip between terminals and watch GPU usage with `nvidia-smi` throughout the pipeline to make sure no “zombie” processes are hanging around. You can also try: `export XLA_CLIENT_MEM_FRACTION=0.5` but this will most likely only help if the issues is thrown during AbMPNN, AF3/Chai, etc.
> 
> Could you share a few more details so we can narrow it down?
> 
> * At what stage of the run do you see the OOM?
> * What GPU are you using and how much memory does it have?
> * What target (or approximate target size)?
> * scFv or nb?
> * The full config you’re running Germinal with.
> 
> That info will make it much easier to reproduce and suggest a concrete fix.

Thank you so much.
